In [3]:
import pandas as pd
import numpy as np
import rpy2.robjects as ro
from rpy2.robjects.packages import importr
from rpy2.robjects import r,pandas2ri
from rpy2.robjects.conversion import localconverter

In [68]:
t0=ro.r['pi']
print(t0[0])

3.141592653589793


In [69]:
t1=ro.r('pi')# 这种方法从某种程度上讲是万能的，因为可以将任意大小和长度的R代码写成一个python字符串，之后通过ro.r('Rcode')调用执行
print(t1[0])
a = ro.r('a<-c(1,2,3)')
print(a)

3.141592653589793
[1] 1 2 3



In [70]:
t2=ro.r.pi# 这种方法对于名称中有“点号”的变量会出问题，比如data.frame/read.csv等
print(t2[0])

3.141592653589793


In [71]:
tmp = ro.r("list(a = matrix(1:10, nrow = 2), b = 'Hello')")
print(tmp)
print(tmp.names)
print(tmp.rx('a'))
print(tmp.rx(1))
print(tmp.rx2(1))
print(tmp.rx2('a').rx(1, 1)) # first element of 'a'
print(tmp.rx2('a').rx(1, True))# first row of 'a'

$a
     [,1] [,2] [,3] [,4] [,5]
[1,]    1    3    5    7    9
[2,]    2    4    6    8   10

$b
[1] "Hello"


[1] "a" "b"

$a
     [,1] [,2] [,3] [,4] [,5]
[1,]    1    3    5    7    9
[2,]    2    4    6    8   10


$a
     [,1] [,2] [,3] [,4] [,5]
[1,]    1    3    5    7    9
[2,]    2    4    6    8   10


     [,1] [,2] [,3] [,4] [,5]
[1,]    1    3    5    7    9
[2,]    2    4    6    8   10

[1] 1

[1] 1 3 5 7 9



In [72]:
ro.r('''
           f <- function(r){pi * r}
           ''')
t3=ro.r['f'](3)
print('%.3f'%t3[0])

9.425


In [79]:
r_script = '''
library(randomForest) # 导入随机森林包
## use data set iris
data = iris # 使用鸢尾花数据集
table(data$Species)
## create a randomForest model to classfy the iris species
# 创建随机森林模型给鸢尾花分类
iris.rf <- randomForest(Species~., data = data, importance=T, proximity=T)
print('--------here is the random model-------')
print(iris.rf)
print('--------here is the names of model-----')
print(names(iris.rf))
confusion = iris.rf$confusion
print(confusion)
table
'''
ro.r(r_script)

[1] "--------here is the random model-------"

Call:
 randomForest(formula = Species ~ ., data = data, importance = T,      proximity = T) 
               Type of random forest: classification
                     Number of trees: 500
No. of variables tried at each split: 2

        OOB estimate of  error rate: 4.67%
Confusion matrix:
           setosa versicolor virginica class.error
setosa         50          0         0        0.00
versicolor      0         47         3        0.06
virginica       0          4        46        0.08
[1] "--------here is the names of model-----"
 [1] "call"            "type"            "predicted"       "err.rate"       
 [5] "confusion"       "votes"           "oob.times"       "classes"        
 [9] "importance"      "importanceSD"    "localImportance" "proximity"      
[13] "ntree"           "mtry"            "forest"          "y"              
[17] "test"            "inbag"           "terms"          
           setosa versicolor virginica class.e

<rpy2.robjects.functions.SignatureTranslatedFunction object at 0x7fbf7df44280> [RTYPES.CLOSXP]
R classes: ('function',)

In [5]:
##python to R
test = ro.DataFrame({'a':[1,2],'b':[3,4]})
test

<rpy2.robjects.vectors.DataFrame object at 0x7fdcc568a180> [RTYPES.VECSXP]
R classes: ('data.frame',)
[IntSexpVec..., IntSexpVec..., IntSexpVec..., IntSexpVec...]
  a.1L: <class 'rpy2.rinterface.IntSexpVector'>
  <rpy2.rinterface.IntSexpVector object at 0x7fdcc56dedc0> [RTYPES.INTSXP]
  a.2L: <class 'rpy2.rinterface.IntSexpVector'>
  <rpy2.rinterface.IntSexpVector object at 0x7fdcc54eccc0> [RTYPES.INTSXP]
  b.3L: <class 'rpy2.rinterface.IntSexpVector'>
  <rpy2.rinterface.IntSexpVector object at 0x7fdcc54ecb40> [RTYPES.INTSXP]
  b.4L: <class 'rpy2.rinterface.IntSexpVector'>
  <rpy2.rinterface.IntSexpVector object at 0x7fdcc54eccc0> [RTYPES.INTSXP]

In [6]:
{'a':[1,2],'b':[3,4]}

{'a': [1, 2], 'b': [3, 4]}

In [85]:
##返回数字和传递参数
add <- function(x,y){
  sum_=x+y
  cat('In R:\t',x,'+',y,'=',sum_,sep = ' ')
  return(sum_)
}

x=4
y=5
res_int =robjects.r.add(x,y)
print(type(res_int))
print(type(res_int[0]))
print(x,' + ',y,' = ',res_int[0])

SyntaxError: invalid syntax. Maybe you meant '==' or ':=' instead of '='? (2180645451.py, line 3)